kubewarden/policy-sdk-go

mod.go

Implement the `protocol_version` callback function that can be used by Go policy authors
Fixes https://github.com/kubewarden/policy-sdk-go/issues/5

Support the `protocol_version` guest callback

---

README.md
kubewarden.go
log_writer.go
log_writer_native.go
log_writer_wasi.go

Extend the SDK to allow policy authors to generate logs from their policies.
Fixes https://github.com/kubewarden/policy-sdk-go/issues/9

Provide logging capabilities

---

go.mod
go.sum

wapc-guest-tinygo works with tinygo >= 0.19.0.

feat: Bump github.com/wapc/wapc-guest-tinygo to v.0.3.1

---

.github/workflows/ci.yml
go.mod
testing/helpers.go

The testing package used to contain some helper methods and types that could be used inside of policy unit tests.
The module defined objects that are now defined inside of the `protocol` package thanks to us leveraging easyjson.
The `testing` code has been updated to:
* Remove types that are now declared inside of the `protocol` package
* Update the functions to make use of the new types used by policies
This is a breaking API change that is going to break old policies unit tests.

fix!: Update testing helpers

---

protocol/types.go
protocol/types_easyjson.go

The previous definition was wrong, `Groups` is a list of strings, not a single string.
The error has been fixed and the easyjson files have been updated.

Fix the UserInfo definition

---

go.mod
go.sum
kubewarden.go
kubewarden_test.go
testing/helpers.go

New method for retrieving a PodSpec given you pass a high level object. Objects supported are: Deployment, ReplicaSet, StatefulSet, DaemonSet, ReplicationController, Job, CronJob, Pod.
This simplifies the evaluation of high level objects. A policy author just need to call this new method and evaluate the PodSpec returned. With this change pod-privileged-policy will reject high level objects (e.g Deployments) instead of allowing them and later rejects the pods
This is to map the Rust feature according to [this issue](https://github.com/kubewarden/kubewarden-controller/issues/392).
Fix #36

Add ExtractPodSpecFromObject

---

go.mod
go.sum
vendor/modules.txt

Update the Golang SDK to use the latest version of the k8s-object module. The new version fix the invalid strfmt version causing issue in the policies build.
Related to https://github.com/kubewarden/safe-labels-policy/pull/16#issuecomment-1469960194

Update k8s objects to v1.24.0-kw4.

---

pkg/capabilities/kubernetes/kubernetes.go
pkg/capabilities/kubernetes/kubernetes_test.go

The Go SDK invoked the wrong host function when listing all the Kubernetes resources.
The issue has been reported by @brunorene

fix: use the correct waPC function to list k8s resources

---

kubewarden.go
kubewarden_test.go

The SDK is using the wrong kind types to extract and update PodSpec in the different Kubernetes kinds supported. This commit fixes the kind names.

fix: wrong Kubernetes kinds.

---

pkg/capabilities/hostcaller_native.go
pkg/capabilities/hostcaller_tinygo.go
pkg/capabilities/hostcaller_wasip1.go
protocol/protocol.go

Allow Wasi policies written using the official Go compiler to be context aware.
The majority of the code taken from this PR is an adaptation of the wapc-tinygo-guest library

feat: make Go Wasi policies context aware

---

pkg/capabilities/kubernetes/kubernetes_test.go
pkg/capabilities/kubernetes/types.go

The `LabelSelector` and `FieldSelector` should not be defaulted to an empty string, they should rather not be sent at all when unset.
To achieve that, they have to be represented with a pointer.
I noticed this behavior while reusing a session recorded with a Rust context aware policy. That doesn't mean the k8s integration has always been broken with Go policies, but we have not been 100% compliant with our spec.

fix: make conformant k8s requests

---

pkg/capabilities/kubernetes/kubernetes_test.go
pkg/capabilities/kubernetes/types.go

Since the namespace could be null when getting cluster-wide resources, we need to change the GetResourceRequest type accordingly.
The current implementation uses the go empty value for strings (`""`) that causes discrepancy when recording/replaying sessions from/to other languages.
For example, before the fix, a rust policy will record:
```
- type: Exchange
request: |
!KubernetesGetResource
api_version: v1
kind: Namespace
name: default
namespace: null
disable_cache: false
response:
type: Success
payload: .....
```
A go policy will record this session instead:
```
- type: Exchange
request: |
!KubernetesGetResource
api_version: v1
kind: Namespace
name: default
namespace: ''
disable_cache: false
response:
type: Success
payload: .....
```
This returns an error when trying to replay the …

fix!: allow namespace to be nil in GetResourceRequest type

---

pkg/capabilities/crypto/crypto.go
pkg/capabilities/crypto/crypto_test.go

Relates to https://github.com/kubewarden/cel-policy/issues/15.
`pkg/capabilities/VerifyCert()` returns a `(bool, err)`. In the case that it returns `(false, err)`, the error is not a runtime error but it may contain the reason for the failed certificate verification.
Return a `(CertificateVerficationResponse{},err)` instead, which contains the bool trusted and a reason, or a runtime error.
CI.

refactor!: return CertificateVerficationResponse{} in VerifyCert()

---

pkg/capabilities/oci/manifest/types.go

Relates to https://github.com/kubewarden/cel-policy/issues/31
Setting the json tags is needed as we marshal this struct in the cel-policy, `kw.oci.getManifest()` function to return it as map.
To honour this new contract with the json tags, mark fields as exported.
This also simplifies creating mocks with this type struct without type casting.
Note that API is still backwards compatible as we were using the fields via the getters, which are untouched. Plus, cel-policy seems to be the first consumer of this. 
CI, and the followup cel-policy PR.

feat: Export and json-tag fields of manifest.OciImageManifestResponse{}

---

pkg/capabilities/oci/verify_v2/types.go
pkg/capabilities/oci/verify_v2/verify_v2.go
pkg/capabilities/oci/verify_v2/verify_v2_test.go

Types used to build host call requests need to be public so we can use them to build mocks in other projects (i.e. cel policy host capabilities mocks)

fix: make verify_v2 types public

---

pkg/capabilities/oci/verify_v2/types.go
pkg/capabilities/oci/verify_v2/verify_v2_test.go

When doing a GH action verification the repository is optional, that means we don't have to send it to the waPC host when it's not set.
Once merged we should tag a patch release of the SDK.

fix: sigstore verification of GH action without repo

---

pkg/capabilities/oci/manifest_config/manifest.go
pkg/capabilities/oci/manifest_config/manifest_test.go
pkg/capabilities/oci/manifest_config/types.go

Adds a new function to allow policy author to get the OCI image manifest and configuration from a given OCI image name.
Fix #87

feat: expose capability to get OCI image configuration.

---

Makefile
log_writer_native.go
log_writer_tinygo.go
pkg/capabilities/hostcaller_gc_wasip1.go
pkg/capabilities/hostcaller_tinygo.go
protocol/protocol.go

Starting from TinyGo 0.32.0 release, the `wasi` target has been renamed to `wasip1` to match the one used by the Go official compiler (aka `gc`).
This change broke some of our build tags. For example, the `protocol` file was no longer built by our wapc policies, causing errors when the policy was being annotated.
This commit changes the build tags to use the `tinygo` build tag to identify builds done by TinyGo. The assumption is: we use TinyGo only to build WebAssembly modules (not to build x86_64 ones), hence we can safely assume that, when this build tag is found, we're building a policy that is meant to be used with WaPC.
Policies being built with older versions of TinyGo will keep working fine, since this build tag has seems to have always been part of TinyGo
Note well: I've renamed …

fix: support changes done by TinyGo 0.32.0

---

.github/workflows/golangci-lint.yml

Updates the golang linter used in the CI workflow to v2.1.0.
Required to make the CI [here](https://github.com/kubewarden/policy-sdk-go/pull/113) happy

chore: updates golang linter.

---

pkg/capabilities/kubernetes/kubernetes.go
pkg/capabilities/kubernetes/kubernetes_test.go
pkg/capabilities/kubernetes/types.go

Part of https://github.com/kubewarden/policy-sdk-go/issues/116
Implement new `CanI()` function capability under the kubernetes capabilities.
This capability checks if the user has permissions to perform an action on resources.
It accepts a `SubjectAccessReviewRequest` struct as input, with its (`spec` as `interface{}`), and returns a `SubjectAccessReviewStatus` struct.
Added a simple unit test.
The structs could come from github.com/kubewarden/k8s-objects instead of declared here.

feat: Add support for can_i host capability
